"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { ChevronLeft, ChevronRight, Eye, Pencil, Plus, Search, Trash2, X } from "lucide-react";

const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000/api/v1";
type Page = { page: number; totalPages: number; total: number };
type Entity = { influencer_key?: string; source_id?: string; name: string; nick_name?: string; subtitle?: string; channel_count?: number; total_channels?: number; total_kols?: number; identity_verified?: boolean; [key: string]: unknown };
type News = { slug: string; sourceUrl: string; title: string; excerpt?: string; category?: string; imageUrl?: string; bodyText?: string; publishedDate?: string };
const emptyPage: Page = { page: 1, totalPages: 0, total: 0 };

function Pager({ page, onChange }: { page: Page; onChange: (next: number) => void }) {
  if (page.totalPages <= 1) return null;
  return <div className="admin-pager"><span>Hiển thị trang {page.page}/{page.totalPages} · {page.total} bản ghi</span><div><button disabled={page.page <= 1} onClick={() => onChange(page.page - 1)} type="button"><ChevronLeft size={16} />Trước</button><button disabled={page.page >= page.totalPages} onClick={() => onChange(page.page + 1)} type="button">Sau<ChevronRight size={16} /></button></div></div>;
}

function DetailPanel({ title, data, onClose }: { title: string; data: Record<string, unknown>; onClose: () => void }) {
  return <section className="admin-record-detail"><button type="button" onClick={onClose}><X size={17} /></button><h3>{title}</h3><div>{Object.entries(data).filter(([, value]) => value !== null && value !== undefined && value !== "").slice(0, 14).map(([key, value]) => <p key={key}><strong>{key.replaceAll("_", " ")}</strong><span>{typeof value === "object" ? JSON.stringify(value) : String(value)}</span></p>)}</div></section>;
}

function NewsDetail({ item, onClose }: { item: News; onClose: () => void }) {
  return <div className="admin-news-modal" role="dialog" aria-modal="true" aria-label="Chi tiết tin tức" onMouseDown={onClose}><section className="admin-record-detail admin-news-detail" onMouseDown={(event) => event.stopPropagation()}><button type="button" onClick={onClose}><X size={17} /></button>{item.imageUrl && <div className="admin-news-detail-image" role="img" aria-label={item.title} style={{ backgroundImage: `url("${item.imageUrl}")` }} />}<span className="admin-news-detail-category">{item.category || "Tin tức"}</span><h3>{item.title}</h3><p className="admin-news-detail-meta">{item.publishedDate ? new Date(item.publishedDate).toLocaleDateString("vi-VN") : "Chưa có ngày đăng"} · {item.slug}</p>{item.excerpt && <p className="admin-news-detail-excerpt">{item.excerpt}</p>}<div className="admin-news-detail-body">{item.bodyText || "Bài viết chưa có nội dung chi tiết."}</div></section></div>;
}

export function AdminEntityManager({ type }: { type: "kols" | "mcns" }) {
  const [items, setItems] = useState<Entity[]>([]); const [query, setQuery] = useState(""); const [page, setPage] = useState(1); const [meta, setMeta] = useState<Page>(emptyPage); const [loading, setLoading] = useState(false); const [selected, setSelected] = useState<Record<string, unknown> | null>(null);
  const label = type === "kols" ? "KOL" : "MCN"; const endpoint = type === "kols" ? "influencers" : "mcns";
  useEffect(() => { const timer = window.setTimeout(() => { setLoading(true); fetch(`${apiUrl}/${endpoint}?limit=20&page=${page}&search=${encodeURIComponent(query)}`).then((response) => response.json()).then((payload) => { setItems(payload.data ?? []); setMeta(payload.pagination ?? emptyPage); }).catch(() => { setItems([]); setMeta(emptyPage); }).finally(() => setLoading(false)); }, 180); return () => window.clearTimeout(timer); }, [endpoint, page, query]);
  const open = async (item: Entity) => { const id = type === "kols" ? item.influencer_key : item.source_id; const response = await fetch(`${apiUrl}/${endpoint}/${id}`); const data = await response.json().catch(() => null); setSelected((data?.data ?? data) as Record<string, unknown>); };
  return <section className="admin-list-card admin-manager"><div className="admin-list-card-heading"><div><h2>Quản lý {label}</h2><p>Tra cứu dữ liệu {label} đang công khai trên hệ thống. Bấm một dòng để xem chi tiết.</p></div><span>{loading ? "Đang tải..." : `${meta.total} bản ghi`}</span></div><label className="admin-manager-search"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Tìm tên ${label}`} /></label><div className="admin-table-wrap"><table><thead><tr><th>{label}</th><th>Thông tin</th><th>Kênh</th><th>Trạng thái</th><th></th></tr></thead><tbody>{items.map((item) => <tr key={item.influencer_key ?? item.source_id} onClick={() => open(item)}><td><strong>{item.name}</strong><small>{item.nick_name || item.subtitle || "—"}</small></td><td>{type === "kols" ? "Nhà sáng tạo nội dung" : `${item.total_kols ?? 0} KOL trực thuộc`}</td><td>{item.channel_count ?? item.total_channels ?? 0}</td><td><span className={`admin-status ${item.identity_verified ? "approved" : "in_review"}`}>{item.identity_verified ? "Đã xác minh" : "Đang hiển thị"}</span></td><td><Eye size={16} /></td></tr>)}{!loading && !items.length && <tr><td className="admin-empty" colSpan={5}>Chưa có dữ liệu phù hợp.</td></tr>}</tbody></table></div><Pager page={meta} onChange={setPage} />{selected && <DetailPanel title={`Chi tiết ${label}`} data={selected} onClose={() => setSelected(null)} />}</section>;
}

const emptyNews: News = { slug: "", sourceUrl: "", title: "", excerpt: "", category: "", imageUrl: "", bodyText: "", publishedDate: new Date().toISOString().slice(0, 10) };
export function AdminNewsManager({ token, editable }: { token: string | null; editable: boolean }) {
  const [items, setItems] = useState<News[]>([]); const [form, setForm] = useState<News>(emptyNews); const [editing, setEditing] = useState(false); const [formOpen, setFormOpen] = useState(false); const [message, setMessage] = useState(""); const [query, setQuery] = useState(""); const [page, setPage] = useState(1); const [meta, setMeta] = useState<Page>(emptyPage); const [selected, setSelected] = useState<News | null>(null);
  const load = useCallback(() => fetch(`${apiUrl}/admin/news?limit=20&page=${page}&search=${encodeURIComponent(query)}`, { headers: { authorization: `Bearer ${token}` } }).then((response) => response.json()).then((payload) => { setItems(payload.data ?? []); setMeta(payload.pagination ?? emptyPage); }).catch(() => { setItems([]); setMeta(emptyPage); }), [token, page, query]);
  useEffect(() => { load(); }, [load]);
  const submit = async (event: FormEvent) => { event.preventDefault(); setMessage(""); const endpoint = editing ? `${apiUrl}/admin/news/${form.slug}` : `${apiUrl}/admin/news`; const response = await fetch(endpoint, { method: editing ? "PATCH" : "POST", headers: { authorization: `Bearer ${token}`, "content-type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json().catch(() => null); if (!response.ok) { setMessage(data?.message ?? "Không thể lưu tin tức."); return; } setForm(emptyNews); setEditing(false); setFormOpen(false); setMessage("Đã lưu tin tức."); load(); };
  const remove = async (slug: string) => { if (!window.confirm("Xóa tin tức này?")) return; const response = await fetch(`${apiUrl}/admin/news/${slug}`, { method: "DELETE", headers: { authorization: `Bearer ${token}` } }); if (!response.ok) { setMessage("Không thể xóa tin tức."); return; } setMessage("Đã xóa tin tức."); load(); };
  const openNews = async (item: News) => { const response = await fetch(`${apiUrl}/news/${item.slug}`); const detail = await response.json().catch(() => null) as Record<string, unknown> | null; setSelected({ ...item, title: String(detail?.title ?? item.title), excerpt: String(detail?.excerpt ?? item.excerpt ?? ""), bodyText: String(detail?.body_text ?? detail?.bodyText ?? item.bodyText ?? ""), imageUrl: String(detail?.image_url ?? detail?.imageUrl ?? item.imageUrl ?? "") }); };
  if (editable && !formOpen) return <section className="admin-list-card admin-manager admin-news-manager"><div className="admin-list-card-heading"><div><h2>Quản lý tin tức</h2><p>Tạo, cập nhật hoặc xóa tin tức hiển thị công khai. Bấm một dòng để xem chi tiết.</p></div><div className="admin-news-toolbar"><span>{meta.total} tin tức</span><button type="button" onClick={() => { setForm(emptyNews); setEditing(false); setFormOpen(true); }}><Plus size={15} />Thêm tin tức</button></div></div><label className="admin-manager-search"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm tiêu đề tin tức" /></label>{message && <p className="admin-news-message">{message}</p>}<div className="admin-table-wrap"><table><thead><tr><th>Tiêu đề</th><th>Chuyên mục</th><th>Ngày đăng</th><th></th></tr></thead><tbody>{items.map((item) => <tr key={item.slug} onClick={() => openNews(item)}><td className="admin-news-title"><strong title={item.title}>{item.title}</strong><small>{item.slug}</small></td><td>{item.category || "—"}</td><td>{item.publishedDate ? new Date(item.publishedDate).toLocaleDateString("vi-VN") : "—"}</td><td className="admin-news-actions" onClick={(event) => event.stopPropagation()}><button type="button" onClick={() => { setForm(item); setEditing(true); setFormOpen(true); }}><Pencil size={14} /></button><button type="button" onClick={() => remove(item.slug)}><Trash2 size={14} /></button></td></tr>)}{!items.length && <tr><td className="admin-empty" colSpan={4}>Chưa có tin tức.</td></tr>}</tbody></table></div><Pager page={meta} onChange={setPage} />{selected && <NewsDetail item={selected} onClose={() => setSelected(null)} />}</section>;
  return <section className="admin-list-card admin-manager admin-news-manager"><div className="admin-list-card-heading"><div><h2>Quản lý tin tức</h2><p>Tạo, cập nhật hoặc xóa tin tức hiển thị công khai. Bấm một dòng để xem chi tiết.</p></div><span>{meta.total} tin tức</span></div>{editable ? <form className="admin-news-form" onSubmit={submit}><input value={form.slug} disabled={editing} onChange={(event) => setForm({ ...form, slug: event.target.value.toLowerCase().replace(/[^a-z0-9-]/g, "-") })} placeholder="slug-bai-viet" required /><input value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="Tiêu đề" required /><input value={form.sourceUrl} onChange={(event) => setForm({ ...form, sourceUrl: event.target.value })} placeholder="Đường dẫn nguồn" required /><input value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })} placeholder="Chuyên mục" /><input value={form.imageUrl} onChange={(event) => setForm({ ...form, imageUrl: event.target.value })} placeholder="URL ảnh" /><input type="date" value={form.publishedDate} onChange={(event) => setForm({ ...form, publishedDate: event.target.value })} /><textarea value={form.excerpt} onChange={(event) => setForm({ ...form, excerpt: event.target.value })} placeholder="Mô tả ngắn" /><textarea value={form.bodyText} onChange={(event) => setForm({ ...form, bodyText: event.target.value })} placeholder="Nội dung bài viết" /><div><button type="submit"><Plus size={15} />{editing ? "Cập nhật" : "Thêm tin tức"}</button>{editing && <button type="button" onClick={() => { setEditing(false); setForm(emptyNews); }}>Hủy</button>}</div></form> : <p className="admin-error">Tài khoản chuyên viên chỉ có quyền xem tin tức.</p>}<label className="admin-manager-search"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm tiêu đề tin tức" /></label>{message && <p className="admin-news-message">{message}</p>}<div className="admin-table-wrap"><table><thead><tr><th>Tiêu đề</th><th>Chuyên mục</th><th>Ngày đăng</th>{editable && <th></th>}</tr></thead><tbody>{items.map((item) => <tr key={item.slug} onClick={() => openNews(item)}><td className="admin-news-title"><strong title={item.title}>{item.title}</strong><small>{item.slug}</small></td><td>{item.category || "—"}</td><td>{item.publishedDate ? new Date(item.publishedDate).toLocaleDateString("vi-VN") : "—"}</td>{editable && <td className="admin-news-actions" onClick={(event) => event.stopPropagation()}><button type="button" onClick={() => { setForm(item); setEditing(true); }}><Pencil size={14} /></button><button type="button" onClick={() => remove(item.slug)}><Trash2 size={14} /></button></td>}</tr>)}{!items.length && <tr><td className="admin-empty" colSpan={editable ? 4 : 3}>Chưa có tin tức.</td></tr>}</tbody></table></div><Pager page={meta} onChange={setPage} />{selected && <NewsDetail item={selected} onClose={() => setSelected(null)} />}</section>;
}
